#!/usr/bin/env bash
set -euo pipefail

ARTIFACT_DIR="${ARTIFACT_DIR:-artifacts/preprod}"
SQL_ARTIFACT_PATH="${SQL_ARTIFACT_PATH:-$ARTIFACT_DIR/migration-dry-run.sql}"

if [[ -z "${PREPROD_DATABASE_URL:-}" ]]; then
  echo "ERROR: PREPROD_DATABASE_URL is required for migration dry-run." >&2
  exit 1
fi

mkdir -p "$ARTIFACT_DIR"

echo "Generating migration dry-run SQL artifact at $SQL_ARTIFACT_PATH"
npx prisma migrate diff \
  --from-url "$PREPROD_DATABASE_URL" \
  --to-schema-datamodel prisma/schema.prisma \
  --script >"$SQL_ARTIFACT_PATH"

if [[ ! -s "$SQL_ARTIFACT_PATH" ]]; then
  echo "-- No SQL output generated by prisma migrate diff." >"$SQL_ARTIFACT_PATH"
fi

echo "Migration dry-run completed."
